### ISSUE TITLE
Issue Related To Directory Structure Conventions

### ISSUE THREAD

**Issue by bennaaym** [dtemir/fellowship-prediction#10]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **What is the current behavior?**
  - Some code files (.py, Procfile) are placed in the repo root folder.
  - Some debugging files (.src/server/api/__pycache__) were committed

* **What is the expected behavior?**
  - All code related files should take place inside the src/ folder 
  - Debugging-related files should be added inside a .gitignore file

**Comment by tashakim** [comment]
pycache have all been deleted, and has been added to .gitignore, so future pycache won't show up

**Comment by tashakim** [comment]
Procfile and wsgi.py was placed in root directory of app for deployment to heroku

**Comment by tashakim** [comment]
Discussed in meeting.
