### ISSUE TITLE
Issue : problem with the structure of data coming from backend

### ISSUE THREAD

**Issue by bennaaym** [dtemir/fellowship-prediction#15]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
* The data coming from the API have the following structure 
* {
    "user": {
        "score": 0,
        "features": {
            "Followers": 3,
            "Repos": 11,
            "Stars": 3,
            "Forks": 0,
            "Commits": 289,
            "Issues": 0,
            "Contributions": 0,
            "Organizations": 1
        }
    },
    "averageFellow": {
        "user": {
            "score": 0,
            "features": {
                "Commits": 892,
                "Followers": 54,
                "Repos": 43,
                "Stars": 26,
                "Forks": 9,
                "Organizations": 1,
                "Issues": 104,
                "Contributions": 86
            }
        }
    }
}

* **If the current behavior is a bug, please provide the steps to reproduce it**
- the JSON format should be changed on the API

* **What is the expected behavior?**
* the data coming from the API should have the following structure
{
    "user": {
        "score": 0,
        "features": {
            "Followers": 3,
            "Repos": 11,
            "Stars": 3,
            "Forks": 0,
            "Commits": 289,
            "Issues": 0,
            "Contributions": 0,
            "Organizations": 1
        }
    },
    "averageFellow": {
            "score": 0,
            "features": {
                "Commits": 892,
                "Followers": 54,
                "Repos": 43,
                "Stars": 26,
                "Forks": 9,
                "Organizations": 1,
                "Issues": 104,
                "Contributions": 86
            }
        }
}

**Comment by tashakim** [comment]
Fixed
