### ISSUE TITLE
"Invalid username"

### ISSUE THREAD

**Issue by stevekm** [dtemir/fellowship-prediction#22]
When I enter my username ("stevekm"), I get the error message "invalid username please try again"

Any ideas?

**Comment by dtemir** [comment]
that's probably because the github token we used expired. let me get back to you!

@mofe64 could you please check if the flask side has an expired token? I can dm you a new one

**Comment by mofe64** [comment]
@dtemir Just added a new token and tested it, It's all good now, @stevekm you can try again.
